name: Say hello

on:
  push:
    branches:
      - master
jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: ECHO THE MESSAGE
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l